const version  = app.assetsVersion;

const assets   = [
    /* Scripts and Stylesheets CDNs */
    'https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.min.js',
    'https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js',
    'https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js',
    'https://cdnjs.cloudflare.com/ajax/libs/i18next/19.7.0/i18next.min.js',
    'https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js',
    'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js',
    'https://cdnjs.cloudflare.com/ajax/libs/Tocca.js/2.0.9/Tocca.min.js',
    'https://cdnjs.cloudflare.com/ajax/libs/video.js/7.11.1/video.min.js',
    'https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js',
    'https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.min.js',
    'https://js.pusher.com/7.0/pusher.min.js',
    'https://js.stripe.com/v3/',
    // 'https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js',
    'https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js',
    'https://unpkg.com/driver.js/dist/driver.min.js',
    'https://webrtc.github.io/adapter/adapter-latest.js',

    /* Scripts and Stylesheets from Squirrel servers */
    distUrl(`assets/caller/caller.js?v-${ version }`),
    distUrl(`assets/camanjs/caman.full.pack.js?v-${ version }`),
    distUrl(`assets/cropper/cropper.js?v-${ version }`),
    distUrl(`assets/js/app.js?v-${ version }`),
    distUrl(`assets/js/birthdays.js?v-${ version }`),
    distUrl(`assets/js/cache.js?v-${ version }`),
    distUrl(`assets/js/channels.js?v-${ version }`),
    distUrl(`assets/js/communities.js?v-${ version }`),
    distUrl(`assets/js/connections.js?v-${ version }`),
    distUrl(`assets/js/content/additional-info-events.js?v-${ version }`),
    distUrl(`assets/js/content/additional-info.js?v-${ version }`),
    distUrl(`assets/js/content/forms.js?v-${ version }`),
    distUrl(`assets/js/content/manager.js?v-${ version }`),
    distUrl(`assets/js/custom.js?v-${ version }`),
    distUrl(`assets/js/custom-validation.js?v-${ version }`),
    distUrl(`assets/js/events.js?v-${ version }`),
    distUrl(`assets/js/file-input-helpers.js?v-${ version }`),
    distUrl(`assets/js/find-friends.js?v-${ version }`),
    distUrl(`assets/js/friend-finder.js?v-${ version }`),
    distUrl(`assets/js/functions.js?v-${ version }`),
    distUrl(`assets/js/get-invite-code.js?v-${ version }`),
    distUrl(`assets/js/helpers.js?v-${ version }`),
    distUrl(`assets/js/help-tours.js?v-${ version }`),
    distUrl(`assets/js/language.js?v-${ version }`),
    distUrl(`assets/js/live.js?v-${ version }`),
    distUrl(`assets/js/main.js?v-${ version }`),
    distUrl(`assets/js/media.js?v-${ version }`),
    distUrl(`assets/js/navigation.js?v-${ version }`),
    distUrl(`assets/js/pusher-manager.js?v-${ version }`),
    distUrl(`assets/js/share.js?v-${ version }`),
    distUrl(`assets/js/sidebar.js?v-${ version }`),
    distUrl(`assets/js/simpleTimer.js?v-${ version }`),
    distUrl(`assets/js/templates/add-event-template.js?v-${ version }`),
    distUrl(`assets/js/templates/channel-settings-template.js?v-${ version }`),
    distUrl(`assets/js/templates/communities-popup-template.js?v-${ version }`),
    distUrl(`assets/js/templates/edit-event-template.js?v-${ version }`),
    distUrl(`assets/js/templates/members-popup-template.js?v-${ version }`),
    distUrl(`assets/js/templates/members-template.js?v-${ version }`),
    distUrl(`assets/js/third-party/edited/intersection-observer.js?v-${ version }`),
    distUrl(`assets/js/third-party/edited/jquery.confirm.min.js?v-${ version }`),
    distUrl(`assets/js/third-party/edited/jquery.mentionable.js?v-${ version }`),
    distUrl(`assets/js/third-party/edited/nuevojs/nuevo.min.js?v-${ version }`),
    distUrl(`assets/js/third-party/edited/prefixfree.min.js?v-${ version }`),
    distUrl(`assets/js/third-party/edited/pulltorefresh.js?v-${ version }`),
    distUrl(`assets/js/third-party/edited/select.min.js?v-${ version }`),
    distUrl(`assets/js/third-party/edited/vue-datetime.js?v-${ version }`),
    distUrl(`assets/js/third-party/edited/webrtc_adaptor.js?v-${ version }`),
    distUrl(`assets/js/third-party/i18nextHttpBackend.min.js?v-${ version }`),
    distUrl(`assets/js/third-party/jquery.mousewheel.min.js?v-${ version }`),
    distUrl(`assets/js/third-party/jquery.urlpreview.js?v-${ version }`),
    distUrl(`assets/js/third-party/luxon.min.js?v-${ version }`),
    distUrl(`assets/js/third-party/owl.carousel.min.js?v-${ version }`),
    distUrl(`assets/js/third-party/progressbar.min.js?v-${ version }`),
    distUrl(`assets/js/third-party/sticky-initial.js?v-${ version }`),
    distUrl(`assets/js/third-party/sticky-kit.min.js?v-${ version }`),
    distUrl(`assets/js/upload-files.js?v-${ version }`),
    distUrl(`assets/js/upload-video.js?v-${ version }`),
    distUrl(`assets/magnific-popup/jquery.magnific-popup.min.js?v-${ version }`),
    distUrl(`assets/moment/min/moment-with-locales.min.js?v-${ version }`),
    distUrl(`assets/nativescript/android-keyboard.js?v-${ version }`),
    distUrl(`assets/nativescript/app.js?v-${ version }`),
    distUrl(`assets/nativescript/get-user-contacts.js?v-${ version }`),
    distUrl(`assets/nativescript/is-native-app.js?v-${ version }`),
    distUrl(`assets/nativescript/lib/nativescript-webview-interface.js?v-${ version }`),
    distUrl(`assets/nativescript/setup.js?v-${ version }`),
    distUrl(`assets/photo-editor/edit-photo.js?v-${ version }`),
    distUrl(`assets/photo-editor/photo-editor-template.js?v-${ version }`),
    distUrl(`assets/photo-editor/upload-photo.js?v-${ version }`),
    distUrl(`assets/smartbanner/smartbanner.min.js?v-${ version }`),
    distUrl(`assets/vimuse/source/js/jquery.hammer-full.min.js?v-${ version }`),
    distUrl(`assets/vimuse/source/js/jquery-ui-1.11.4.sortable.min.js?v-${ version }`),
    distUrl(`assets/vimuse/source/js/jquery.ui.touch-punch-improved.js?v-${ version }`),
    distUrl(`assets/vimuse/source/js/jquery.vimuse.min.js?v-${ version }`),
    distUrl(`assets/vimuse/source/js/perfect-scrollbar.jquery.min.js?v-${ version }`),
    distUrl(`assets/vimuse/source/mediaelement/mediaelement-and-player.min.js?v-${ version }`),

    /* Emojis */
    baseUrl(`assets/smileys/3dmovie.svg`),
    baseUrl(`assets/smileys/angry.svg`),
    baseUrl(`assets/smileys/badthoughts.svg`),
    baseUrl(`assets/smileys/bigsmilebash.svg`),
    baseUrl(`assets/smileys/bigsmileD.svg`),
    baseUrl(`assets/smileys/bigsmileeyes.svg`),
    baseUrl(`assets/smileys/bigsmile.svg`),
    baseUrl(`assets/smileys/concerned.svg`),
    baseUrl(`assets/smileys/cool.svg`),
    baseUrl(`assets/smileys/cry.svg`),
    baseUrl(`assets/smileys/cutebow.svg`),
    baseUrl(`assets/smileys/eek.svg`),
    baseUrl(`assets/smileys/evilangry.svg`),
    baseUrl(`assets/smileys/expel.svg`),
    baseUrl(`assets/smileys/expletive.svg`),
    baseUrl(`assets/smileys/fireeyes.svg`),
    baseUrl(`assets/smileys/full.svg`),
    baseUrl(`assets/smileys/gross.svg`),
    baseUrl(`assets/smileys/happyeyes.svg`),
    baseUrl(`assets/smileys/happy.svg`),
    baseUrl(`assets/smileys/hat.svg`),
    baseUrl(`assets/smileys/heartbreak.svg`),
    baseUrl(`assets/smileys/hearteyes1.svg`),
    baseUrl(`assets/smileys/hearteyes2.svg`),
    baseUrl(`assets/smileys/heart.svg`),
    baseUrl(`assets/smileys/hello.svg`),
    baseUrl(`assets/smileys/hi.svg`),
    baseUrl(`assets/smileys/injured.svg`),
    baseUrl(`assets/smileys/lol.svg`),
    baseUrl(`assets/smileys/love.svg`),
    baseUrl(`assets/smileys/mad.svg`),
    baseUrl(`assets/smileys/missyou2.svg`),
    baseUrl(`assets/smileys/missyou.svg`),
    baseUrl(`assets/smileys/money.svg`),
    baseUrl(`assets/smileys/mustache.svg`),
    baseUrl(`assets/smileys/nananabooboo.svg`),
    baseUrl(`assets/smileys/nerd.svg`),
    baseUrl(`assets/smileys/nice.svg`),
    baseUrl(`assets/smileys/no.svg`),
    baseUrl(`assets/smileys/ooh.svg`),
    baseUrl(`assets/smileys/party.svg`),
    baseUrl(`assets/smileys/purpletongue.svg`),
    baseUrl(`assets/smileys/relief.svg`),
    baseUrl(`assets/smileys/sauced.svg`),
    baseUrl(`assets/smileys/scared.svg`),
    baseUrl(`assets/smileys/shocked.svg`),
    baseUrl(`assets/smileys/sick.svg`),
    baseUrl(`assets/smileys/starstruck.svg`),
    baseUrl(`assets/smileys/sunglasses.svg`),
    baseUrl(`assets/smileys/thankyou.svg`),
    baseUrl(`assets/smileys/winksilly.svg`),
    baseUrl(`assets/smileys/winksmile.svg`),
    baseUrl(`assets/smileys/yes.svg`),
    baseUrl(`assets/smileys/zombie.svg`),
    baseUrl(`assets/smileys/zzz.svg`),

    /* Site icons */
    // baseUrl('assets/images/site_icon/TODO'),

    /* Fonts */
    baseUrl(`assets/fonts/segoeui.ttf`),
    baseUrl(`assets/fonts/segoeuisb.ttf`),
];

window.updateCache = () => {
    if (! 'caches' in window || ! 'serviceWorker' in navigator) {
        return console.log('Some required caching libraries are not supported in this browser: assets caching is disabled.');
    }

    console.log('Updating assets to version', version);

    caches.delete('squirrel').then(
        () => caches.open('squirrel').then(cache => cache.addAll(assets))
    );
}
