videojs.addLanguage(window.app.constants.LANGUAGE_CODE, {
  "Audio Player": translate("Audio Player"),
  "Video Player": translate("Video Player"),
  "Play": translate("Play"),
  "Pause": translate("Pause"),
  "Replay": translate("Replay"),
  "Current Time": translate("Current Time"),
  "Duration": translate("Duration"),
  "Remaining Time": translate("Remaining Time"),
  "Stream Type": translate("Stream Type"),
  "LIVE": translate("LIVE"),
  "Seek to live, currently behind live": translate("Seek to live, currently behind live"),
  "Seek to live, currently playing live": translate("Seek to live, currently playing live"),
  "Loaded": translate("Loaded"),
  "Progress": translate("Progress"),
  "Progress Bar": translate("Progress Bar"),
  "progress bar timing: currentTime={1} duration={2}": translate("{1} of {2}"),
  "Fullscreen": translate("Fullscreen"),
  "Non-Fullscreen": translate("Non-Fullscreen"),
  "Mute": translate("Mute"),
  "Unmute": translate("Unmute"),
  "Playback Rate": translate("Playback Rate"),
  "Subtitles": translate("Subtitles"),
  "subtitles off": translate("subtitles off"),
  "Captions": translate("Captions"),
  "captions off": translate("captions off"),
  "Chapters": translate("Chapters"),
  "Descriptions": translate("Descriptions"),
  "descriptions off": translate("descriptions off"),
  "Audio Track": translate("Audio Track"),
  "Volume Level": translate("Volume Level"),
  "You aborted the media playback": translate("You aborted the media playback"),
  "A network error caused the media download to fail part-way.": translate("A network error caused the media download to fail part-way."),
  "The media could not be loaded, either because the server or network failed or because the format is not supported.": translate("The media could not be loaded, either because the server or network failed or because the format is not supported."),
  "The media playback was aborted due to a corruption problem or because the media used features your browser did not support.": translate("The media playback was aborted due to a corruption problem or because the media used features your browser did not support."),
  "No compatible source was found for this media.": translate("No compatible source was found for this media."),
  "The media is encrypted and we do not have the keys to decrypt it.": translate("The media is encrypted and we do not have the keys to decrypt it."),
  "Play Video": translate("Play Video"),
  "Close": translate("Close"),
  "Close Modal Dialog": translate("Close Modal Dialog"),
  "Modal Window": translate("Modal Window"),
  "This is a modal window": translate("This is a modal window"),
  "This modal can be closed by pressing the Escape key or activating the close button.": translate("This modal can be closed by pressing the Escape key or activating the close button."),
  ", opens captions settings dialog": translate(", opens captions settings dialog"),
  ", opens subtitles settings dialog": translate(", opens subtitles settings dialog"),
  ", opens descriptions settings dialog": translate(", opens descriptions settings dialog"),
  ", selected": translate(", selected"),
  "captions settings": translate("captions settings"),
  "subtitles settings": translate("subtitles settings"),
  "descriptions settings": translate("descriptions settings"),
  "Text": translate("Text"),
  "White": translate("White"),
  "Black": translate("Black"),
  "Red": translate("Red"),
  "Green": translate("Green"),
  "Blue": translate("Blue"),
  "Yellow": translate("Yellow"),
  "Magenta": translate("Magenta"),
  "Cyan": translate("Cyan"),
  "Background": translate("Background"),
  "Window": translate("Window"),
  "Transparent": translate("Transparent"),
  "Semi-Transparent": translate("Semi-Transparent"),
  "Opaque": translate("Opaque"),
  "Font Size": translate("Font Size"),
  "Text Edge Style": translate("Text Edge Style"),
  "None": translate("None"),
  "Raised": translate("Raised"),
  "Depressed": translate("Depressed"),
  "Uniform": translate("Uniform"),
  "Dropshadow": translate("Dropshadow"),
  "Font Family": translate("Font Family"),
  "Proportional Sans-Serif": translate("Proportional Sans-Serif"),
  "Monospace Sans-Serif": translate("Monospace Sans-Serif"),
  "Proportional Serif": translate("Proportional Serif"),
  "Monospace Serif": translate("Monospace Serif"),
  "Casual": translate("Casual"),
  "Script": translate("Script"),
  "Small Caps": translate("Small Caps"),
  "Reset": translate("Reset"),
  "restore all settings to the default values": translate("restore all settings to the default values"),
  "Done": translate("Done"),
  "Caption Settings Dialog": translate("Caption Settings Dialog"),
  "Beginning of dialog window. Escape will cancel and close the window.": translate("Beginning of dialog window. {{ escape }} will cancel and close the window.", {escape: 'Escape'}),
  "End of dialog window.": translate("End of dialog window."),
  "{1} is loading.": translate("{1} is loading."),
  "Exit Picture-in-Picture": translate("Exit Picture-in-Picture"),
  "Picture-in-Picture": translate("Picture-in-Picture"),
  "Quality": translate("Quality"),
  "Settings": translate("Settings"),
  "Related": translate("Related"),
  "Share": translate("Share"),
  "Speed": translate("Speed"),
  "Zoom:": translate("Zoom"),
  "Link": translate("Link"),
  "Embed": translate("Embed"),
  "Social": translate("Social"),
  "Check out this cool video on": translate("Check out this cool video on"),
  "RESET": translate("RESET"),
  "Zoom": translate("Zoom"),
  "ZOOM HELP": translate("ZOOM HELP"),
  "Use ZOOM slider or mouse wheel to ZOOM in video.": translate("Use ZOOM slider or mouse wheel to ZOOM in video."),
  "Drag zoomed area using your mouse or a finger.": translate("Drag zoomed area using your mouse or a finger."),
  "Forward": translate("Forward"),
  "Rewind":  translate("Rewind"),
  "Mirror view": translate("Mirror view"),
  "Theater mode": translate("Theater mode"),
  "Advertisement": translate("Advertisement"),
  "Skip Ad in": translate("Skip Ad in"),
  "Skip Now!": translate("Skip Now!"),
  "Watch full video on": translate("Watch full video on"),
  "Casting to": translate("Casting to"),
  "Auto": translate("Automatic")
});
